# Generated by Django 4.2 on 2023-05-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('movement_id', models.IntegerField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bed')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.room')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.visit')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.ward')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.ward'),
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.IntegerField()),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.stay')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='wards',
            field=models.ManyToManyField(to='dashboard.ward'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.room'),
        ),
    ]
