# Generated by Django 4.2 on 2023-06-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('H', 'Hospital'), ('D', 'Department'), ('W', 'Ward'), ('R', 'Room')], default='H', max_length=1)),
                ('theme_type', models.CharField(choices=[('I', 'Information'), ('B', 'All Beds'), ('R', 'All Rooms'), ('W', 'All Wards'), ('D', 'All Departments'), ('H', 'History')], default='I', max_length=1)),
                ('time_type', models.CharField(choices=[('N', 'Neartime'), ('T', 'Time'), ('P', 'Period')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Mann'), ('F', 'Frau'), ('D', 'Divers')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_activation', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserDataRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('data_representation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.datarepresentation')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.department')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.user')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.ward')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='data_representations',
            field=models.ManyToManyField(through='dashboard.UserDataRepresentation', to='dashboard.datarepresentation'),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('movement_id', models.IntegerField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bed')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.room')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.visit')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.ward')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.ward'),
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.IntegerField()),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.stay')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='wards',
            field=models.ManyToManyField(to='dashboard.ward'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.room'),
        ),
    ]
