# Generated by Django 4.2 on 2023-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatarepresentation',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
