# Generated by Django 4.2 on 2023-06-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userdatarepresentation_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatarepresentation',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='datarepresentation',
            unique_together={('location_type', 'theme_type', 'time_type')},
        ),
    ]
