# Generated by Django 4.2 on 2023-08-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='stay',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stay'),
        ),
    ]
