# Generated by Django 4.2 on 2023-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_bed_date_of_activation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdatarepresentation',
            name='department',
        ),
        migrations.AlterField(
            model_name='bed',
            name='date_of_activation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bed',
            name='date_of_expiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bed',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datarepresentation',
            name='location_type',
            field=models.CharField(choices=[('H', 'Hospital'), ('W', 'Ward'), ('R', 'Room')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='datarepresentation',
            name='theme_type',
            field=models.CharField(choices=[('I', 'Information'), ('B', 'All Beds'), ('R', 'All Rooms'), ('W', 'All Wards'), ('H', 'History')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_of_activation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_of_expiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stay',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userdatarepresentation',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userdatarepresentation',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='admission_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='discharge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='date_of_activation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ward',
            name='date_of_expiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
