# Generated by Django 4.2 on 2023-06-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_stay_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
