# Generated by Django 4.2 on 2023-06-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_bed_id_alter_room_id_alter_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room'),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stay'),
        ),
        migrations.AlterField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ward'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bed'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.visit'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ward'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
        ),
    ]
